config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations' }
  
  resources :users
  resources :products
  resources :categories

  resources :posts do
    resources :comments
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, :description, :url_seo, presence: true
    validates :name, :description, :url_seo, uniqueness: true
    has_many :products
    has_rich_text :description
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
  broadcasts_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :content, presence: true
    validates :title, uniqueness: true
    has_rich_text :content
    has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :title, uniqueness: true
    has_rich_text :long_text
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :confirmable,
         :recoverable, :rememberable, :validatable, :lockable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!, only: [:index]
    # skip_before_action :authenticate_user!
    # before_action :authenticate_user!

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all
    end

    def show
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
    
        respond_to do |format|
          if @category.save
            format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
            format.json { render :show, status: :created, location: @category }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @category.errors, status: :unprocessable_entity }
          end
        end
      end


      private
      def category_params
        params.require(:category).permit(:name, :description, :url_seo)
      end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy]
    before_action :set_post

def create
    comment = @post.comments.create! params.required(:comment).permit(:content)
    CommentsMailer.submitted(comment).deliver_later
    redirect_to @post
end

def destroy
    comment = @post.comments.find(params[:id])
    comment.destroy

    redirect_to do |format| 
        format.html { redirect_to @post, notice: "Comment was successfully destroyed."}
        format.json { head :no_content }
    end
end

private
    def set_post
        @post = Post.find(params[:post_id])
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params)

        if @product.save
            redirect_to product_url(@product), notice: "Product was successfully created."
        else
            render :new, status: :unprocessable_entity
        end

    end
    

    def update

        @product = Product.find(params[:id])

        if @product.update(product_params)
            redirect_to product_url(@product), notice: "Product was successfully updated."
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to products_path, status: :see_other
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :long_text, :short_text, :youtube_url)
    end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource) # In case you want to sign in the user
      users_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authenticate_user!

    def index
        @users = User.all
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        
        redirect_to users_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
    <% if category.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
            <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>   

    <div class="my-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
        <%= form.label :description %>
        <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
        <%= form.label :url_seo %>
        <%= form.text_field :url_seo, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 hover:bg-blue-400 text-white inline-block font-medium cursor-pointer" %>
    </div>
<% end %>  

app/views/categories/index.html.erb
<div class="container mx-auto">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to 'New category', new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 hover:bg-blue-400 text-white block font-medium" %>
  </div>

  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full">
            <thead class="bg-white border-b">
                <tr>
                  <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Category name</th>
                </tr>
              </thead>
              <tbody>
                <%= render @categories %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New category</h1>

    <%= render "form", category: @category %>

    <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>


</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
    <%= comment.content %>
    <%= time_tag comment.created_at, "data-local": "time-ago" %>
    <%= link_to "Destroy", [comment.post, comment], data:{turbo_method: :delete, turbo_confirm: "Are you sure?", } %>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [ post, Comment.new ] do |form| %>

    <div class="block mb-2 text-sm text-gray-600">Your comment:</div>
    <%= form.text_area :content, class: "w-full px-3 py-2 placeholder-gray-300 border border-gray-300 rounded-md  focus:outline-none focus:ring focus:ring-indigo-100 focus:border-indigo-300" %>
    <%= form.submit class: "w-full px-2 py-4 text-white bg-indigo-500 rounded-md  focus:bg-indigo-600 focus:outline-none" %>
<% end %> 

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body class="text-gray-700 bg-white" style="font-family: 'Source Sans Pro', sans-serif">

    <div class="relative bg-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6">
        <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
          <div class="flex justify-start lg:w-0 lg:flex-1">
            <a href="<%= root_path %>">
              <span class="sr-only">Workflow</span>
              <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="">
            </a>
          </div>
          <div class="-mr-2 -my-2 md:hidden">
            <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
              <span class="sr-only">Open menu</span>
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
          <nav class="hidden md:flex space-x-10">
          <% if user_signed_in? %>
            <%= link_to "Home", root_path, class: "text-base font-medium text-gray-500 hover:text-gray-900" %>
            <%= link_to "Products", products_path, class: "text-base font-medium text-gray-500 hover:text-gray-900" %>
            <%= link_to "Users", users_path, class: "text-base font-medium text-gray-500 hover:text-gray-900" %>
          <% else %>
            <%= link_to "Home", root_path, class: "text-base font-medium text-gray-500 hover:text-gray-900" %>
          <% end %>
          </nav>
          <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
            <% if user_signed_in? %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900" %><br>
              <%= link_to "Edit user", edit_user_registration_path, class: "ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-blue-600 hover:bg-blue-400" %>

              <%# <%= button_to "Log out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900" %><br>
              <%= link_to "Register", new_user_registration_path, class: "ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-blue-600 hover:bg-blue-400" %>
            <% end %>
          </div>
        </div>
      </div>
      
    </div>
  
    <main class="max-w-7xl mx-auto px-5 py-10 sm:px-6">
      <% if flash[:notice] %>
          <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block"><%= notice %></p>
      <% end %>

      <% if flash[:alert] %>
          <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block"><%= alert %></p>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_comments.html.erb
<div class="my-5">
    <h2>Comments</h2>

    <div id="comments" class="my-5">
        <%= render post.comments %>
    </div>

    <%= render "comments/new", post: post %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.rich_text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 hover:bg-blue-400 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title: <%= post.title %></strong>
  </p>

  <p>
    <%# 
    Not working as should example "10 min ago" 
    importmap.rb - local-time not imported 
    './bin/importmap pin local-time' is not working on windows 
    %>
    Posted: <%= time_tag post.created_at, "data-local": "time-ago" %> 
  </p>

  <p>
    <%= pluralize post.comments.count, "comment" %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= post.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this post", post, class: "rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
    <%= link_to "Edit this post", edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
    <%= link_to "Destroy", post, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium", data:{turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full">

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 hover:bg-blue-400 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>

<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @post %>

    <%= render "posts/comments", post: @post %>

    <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 font-medium" %>
    </div>
    <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>


    <div class="my-5">
        <%= form.label :title %>
        <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <%= form.select :category, Category.all, :prompt => "Select One" %>

    <div class="my-5">
        <%= form.label :short_text %>
        <%= form.rich_text_area :short_text, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
        <%= form.label :youtube_url %>
        <%= form.text_field :youtube_url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
        <%= form.label :long_text %>
        <%= form.rich_text_area :long_text, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
        <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 hover:bg-blue-400 text-white inline-block font-medium cursor-pointer" %>
    </div>

<% end %>

app/views/products/_product.html.erb
<tr class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
<td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"><%= link_to product.title, product %></td>
<td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap"> </td>
</tr>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="container mx-auto">

<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Product</th>
                <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">Category</th>
              </tr>
            </thead>
            <tbody>
              <%= render @products %>
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</div>

<%= link_to 'New product', new_product_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
  <div>
    <div class="text-xl font-medium text-gray-800 font-bold mb-3"><%= @product.title %></div>
    <p class="text-gray-600 mb-8"><%= sanitize @product.short_text %></p>

  </div>
  <div class="flex flex-wrap">
    <div class="w-1/3 md:w-1/3">
      <iframe width="350" height="252" src="<%= @product.youtube_url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    
    <div class="w-1/2 md:w-1/2">
      <p class="text-slate-500 mb-8"><%= @product.long_text %></p>
    </div>
  </div>



    <%= link_to 'Edit this product', edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= link_to 'Destroy this product', product_path(@product), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 font-medium" %>
    </div>

<%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-300 inline-block font-medium" %>

app/views/users/_user.html.erb
userid: <%= user.id %><br>
email: <%= user.email %><br>

<%= 'sign_in_count'.humanize  %><br>
<%= user.sign_in_count %><br>

<%= 'current_sign_in_at'.humanize  %>
<%= user.current_sign_in_at %>

<%= 'last_sign_in_at'.humanize  %>
<%= user.last_sign_in_at %><br>

<%= 'current_sign_in_ip'.humanize  %>
<%= user.current_sign_in_ip %>

<%= 'last_sign_in_ip'.humanize  %>
<%= user.last_sign_in_ip %><br>

<%= 'confirmed_at'.humanize  %>
<%= user.confirmed_at %><br>

<%= 'confirmation_sent_at'.humanize  %>
<%= user.confirmation_sent_at %><br>

<%= 'unconfirmed_email'.humanize  %>
<%= user.unconfirmed_email %><br>

<%= 'confirmation_token'.humanize  %>
<%= user.confirmation_token %><br>

# Erorr it Deletes all users 
<%= link_to "Destroy", user, 
    class: "whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-gray-600 hover:bg-gray-400",
    data:{turbo_method: :delete, turbo_confirm: "Are you sure?" } 
%>

<hr>

app/views/users/index.html.erb
Users: <%= User.count %>
<hr>

<%= render @users %>